jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        directories:
            Tactician:
                namespace_prefix: "League\\Tactician\\Bundle\\Middleware"
                path: "%kernel.project_dir%/config/serializer/tactician"