rest_controllers:
    resource: ../../src/Interfaces/Http/Rest/Controller/*
    type: annotation
    prefix: /api
    defaults: { _format: json }

web_controllers:
    resource: ../../src/Interfaces/Http/Web/Controller/*
    type: annotation